server:
  port: 8084

spring:
  config:
    activate:
      on-profile: default
  application:
    name: prendas
  datasource:
    url: jdbc:mysql://${prendas-db:localhost}:${production-port:3311}/prendas
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
