server:
  port: 8083

spring:
  config:
    activate:
      on-profile: default
  application:
    name: recursos
  datasource:
    url: jdbc:mysql://${recursos-db:localhost}:${production-port:3310}/recursos
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

resilience4j:
  circuitbreaker:
    configs:
      shared:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      prendas:
        base-config: shared
      familias:
        base-config: shared
    timelimiter:
      configs:
        shared:
        timeout-duration: 2s
        cancel-running-future: true
      instances:
        prendas:
          base-config: shared
        familias:
          base-config: shared